### ISSUE TITLE
LPM fails to follow HTTP redirects

### ISSUE THREAD

**Issue by headj-origami** [liquibase/liquibase-package-manager#286]
**Describe the bug**
If lpm is run in an environment that it has to follow a redirect to download a package (in our case, running in a kubernetes pod with an Istio sidecar), the deployment fails with error code 1 and error:
```
Unable to download from <url>
```

**To Reproduce**
1. Create a docker image running an lpm install
e.g.
```
FROM liquibase/liquibase:4.15.0

RUN lpm add mysql --global
```
2. Deploy this container with an Istio sidecar
3. Check container logs

**Expected behavior**
LPM follows the istio redirect and successfully downloads the package

**Additional context**
I believe the issue here is [this redirect handling](https://github.com/liquibase/liquibase-package-manager/blob/master/internal/app/utils/Http.go#L16).

Per the [go docs](https://pkg.go.dev/net/url#URL.String), if URL.Opaque is set, the url is constructed as `<scheme>:<opaque>?<query>#<fragment>`, instead of `<scheme>://<user>@<host>/<path>?<query>#<fragment>`.

So, by setting `URL.Opaque` to `URL.Path` you're dropping the host information.

For example, if attempting to download:
```
https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar```
you'd instead attempt to GET:
```
https://maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar
```

But because the Reidrect handler doesn't actually change the `url` variable, the error logging still would report:
```
Unable to download from https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar
```

**Comment by mcred** [comment]
Pushed an update that should fix this. If you can check out and run `make build` to confirm for your OS, let me know if you have issues. Alternatively tell me which artifact you usually download and I can put a pre-release build here for you to test.

**Comment by headj-origami** [comment]
We're making use of the liquibase/liquibase docker image within our builds, which is based on an ubuntu base layer I believe.

Could either provide an alternative docker image, or an ubuntu-compatible amd64 binary for lpm which we can add to our dockerfile?

**Comment by mcred** [comment]
[lpm-0.2.4-linux.zip](https://github.com/liquibase/liquibase-package-manager/files/12429995/lpm-0.2.4-linux.zip)

Let me know if this version solves your issue.

**Comment by headj-origami** [comment]
Unfortunately, this didn't solve the issue.
With the new lpm binary, the package get still failed with an istio sidecar.

For reference, this is the minimal dockerfile we're using (including the binary patch):


```
FROM liquibase/liquibase:4.15.0

COPY lpm.zip .
RUN rm /liquibase/bin/lpm
RUN unzip lpm.zip -d /liquibase/bin/
RUN rm lpm.zip

RUN lpm add mysql --global

CMD []
```

And this is the build log output:
```
Step 1/10 : FROM liquibase/liquibase:4.15.0
4.15.0: Pulling from liquibase/liquibase
3b65ec22a9e9: Pulling fs layer
884d36886594: Pulling fs layer
3183ef2f0718: Pulling fs layer
048cc7121983: Pulling fs layer
5406a7552d58: Pulling fs layer
250896aa22c4: Pulling fs layer
8ea2502785eb: Pulling fs layer
28cae89b26d6: Pulling fs layer
4f4fb700ef54: Pulling fs layer
71c9c1c0bbfd: Pulling fs layer
12a27a91b4ca: Pulling fs layer
15b3888d00ec: Pulling fs layer
850dcf9a2218: Pulling fs layer
943339ee5e11: Pulling fs layer
157b76cb8b82: Pulling fs layer
9faf80f14f90: Pulling fs layer
03b2c98d8324: Pulling fs layer
bef7e684ca4c: Pulling fs layer
d980b98d112a: Pulling fs layer
28cae89b26d6: Waiting
4f4fb700ef54: Waiting
71c9c1c0bbfd: Waiting
12a27a91b4ca: Waiting
15b3888d00ec: Waiting
850dcf9a2218: Waiting
943339ee5e11: Waiting
157b76cb8b82: Waiting
9faf80f14f90: Waiting
03b2c98d8324: Waiting
bef7e684ca4c: Waiting
d980b98d112a: Waiting
048cc7121983: Waiting
5406a7552d58: Waiting
250896aa22c4: Waiting
884d36886594: Verifying Checksum
884d36886594: Download complete
3b65ec22a9e9: Verifying Checksum
3b65ec22a9e9: Download complete
3183ef2f0718: Verifying Checksum
3183ef2f0718: Download complete
048cc7121983: Verifying Checksum
048cc7121983: Download complete
250896aa22c4: Verifying Checksum
250896aa22c4: Download complete
8ea2502785eb: Verifying Checksum
8ea2502785eb: Download complete
5406a7552d58: Verifying Checksum
5406a7552d58: Download complete
28cae89b26d6: Verifying Checksum
28cae89b26d6: Download complete
4f4fb700ef54: Download complete
71c9c1c0bbfd: Verifying Checksum
71c9c1c0bbfd: Download complete
15b3888d00ec: Download complete
3b65ec22a9e9: Pull complete
850dcf9a2218: Verifying Checksum
850dcf9a2218: Download complete
943339ee5e11: Verifying Checksum
943339ee5e11: Download complete
157b76cb8b82: Verifying Checksum
157b76cb8b82: Download complete
9faf80f14f90: Verifying Checksum
9faf80f14f90: Download complete
03b2c98d8324: Verifying Checksum
03b2c98d8324: Download complete
12a27a91b4ca: Verifying Checksum
12a27a91b4ca: Download complete
bef7e684ca4c: Verifying Checksum
bef7e684ca4c: Download complete
d980b98d112a: Download complete
884d36886594: Pull complete
3183ef2f0718: Pull complete
048cc7121983: Pull complete
5406a7552d58: Pull complete
250896aa22c4: Pull complete
8ea2502785eb: Pull complete
28cae89b26d6: Pull complete
4f4fb700ef54: Pull complete
71c9c1c0bbfd: Pull complete
12a27a91b4ca: Pull complete
15b3888d00ec: Pull complete
850dcf9a2218: Pull complete
943339ee5e11: Pull complete
157b76cb8b82: Pull complete
9faf80f14f90: Pull complete
03b2c98d8324: Pull complete
bef7e684ca4c: Pull complete
d980b98d112a: Pull complete
Digest: sha2[56](https://gitlab.com/OrigamiEnergyLtd/platform-engineering/identity/opa-data/-/jobs/4980415541#L56):9badb9e61ec83e6f0521b789[57](https://gitlab.com/OrigamiEnergyLtd/platform-engineering/identity/opa-data/-/jobs/4980415541#L57)5535623e9ec3a2e13f4ae97d12db3a87a22248
Status: Downloaded newer image for liquibase/liquibase:4.15.0
 ---> 30[59](https://gitlab.com/OrigamiEnergyLtd/platform-engineering/identity/opa-data/-/jobs/4980415541#L59)02ee626e
Step 2/10 : COPY db.changelog-master.yaml /liquibase/changelog/
 ---> 1438c69f332f
Step 3/10 : COPY --chown=liquibase:liquibase lpm.zip .
 ---> d64ffb4d6d6a
Step 4/10 : RUN rm /liquibase/bin/lpm
 ---> Running in c2a394076512
Removing intermediate container c2a394076512
 ---> 82[61](https://gitlab.com/OrigamiEnergyLtd/platform-engineering/identity/opa-data/-/jobs/4980415541#L61)4ba0f591
Step 5/10 : RUN unzip lpm.zip -d /liquibase/bin/
 ---> Running in 5e4afb7041ee
Archive:  lpm.zip
  inflating: /liquibase/bin/lpm      
Removing intermediate container 5e4afb7041ee
 ---> 3fd426b41836
Step 6/10 : COPY --chown=liquibase:liquibase oe-entrypoint.sh /usr/local/bin/
 ---> 882c200d2619
Step 7/10 : RUN chmod 0755 /usr/local/bin/oe-entrypoint.sh
 ---> Running in 33946c97[65](https://gitlab.com/OrigamiEnergyLtd/platform-engineering/identity/opa-data/-/jobs/4980415541#L65)19
Removing intermediate container 33946c976519
 ---> d7a2b305d1ef
Step 8/10 : RUN lpm add mysql --global
 ---> Running in af[66](https://gitlab.com/OrigamiEnergyLtd/platform-engineering/identity/opa-data/-/jobs/4980415541#L66)7bd0[80](https://gitlab.com/OrigamiEnergyLtd/platform-engineering/identity/opa-data/-/jobs/4980415541#L80)07
Unable to download from https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar
The command '/bin/sh -c lpm add mysql --global' returned a non-zero code: 1
```

**Comment by mcred** [comment]
I'll need some more information to look into this. Removing the custom redirect behavior in [this commit](https://github.com/liquibase/liquibase-package-manager/commit/f1a78608773c760e9fb3dfe1fd6c730ebfa99f22) would make the `http.Client{}` follow the default redirect behavior. Can you try removing `lpm add mysql --global` from the Dockerfile, for now, and running that command in a pod with some trace-routes? I'm not sure where the redirect is happening or why the default redirect behavior doesn't work. Could you also try a direct CURL or WGET of `https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar` with verbose output?
